// <auto-generated />
using ApiProducto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProducto.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiProducto.Models.Administracion.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"), 1L, 1);

                    b.Property<string>("Apellidos_Usuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Correo_Usuario")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono_Celular")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiProducto.Models.Ventas.Proveedor", b =>
                {
                    b.Property<int>("ID_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Proveedor"), 1L, 1);

                    b.Property<string>("Mercaderia_Producto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre_Proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Proveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("BanckPruebaAngular.Models.Ventas.Producto", b =>
                {
                    b.Property<int>("ID_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Producto"), 1L, 1);

                    b.Property<string>("Cantidad_iva")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Graba_iva")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Precio_PVP")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Precio_con_iva")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Precio_sin_iva")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Producto");

                    b.ToTable("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
